In [1]:
import torch

In [2]:
A = torch.tensor([[1., 2.], [1., 2.]])
A

tensor([[1., 2.],
        [1., 2.]])

In [3]:
B = torch.tensor([[2., 1.], [-1., -2.]])
B

tensor([[ 2.,  1.],
        [-1., -2.]])

In [4]:
A @ B

tensor([[ 0., -3.],
        [ 0., -3.]])

In [5]:
def matmult(A, B):
    ar, ac = A.shape
    br, bc = B.shape
    assert ac == br
    
    C = torch.zeros(ar, bc)    
    for i in range(ar):
        for j in range(bc):
            for k in range(ac):
                C[i, j] += A[i, k] * B[k, j]
    
    return C

In [6]:
%timeit matmult(A, B)

214 µs ± 2.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
def matmult(A, B):
    ar, ac = A.shape
    br, bc = B.shape
    assert ac == br
    
    C = torch.einsum("ik,kj->ij", A, B)
    
    return C

In [8]:
%timeit matmult(A, B)

38.4 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%timeit A.matmul(B)

4.09 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
